format
    PAGEMIE                            D00063F.
    PATTBUD                            YESN01F.
    PATTCRC                            YESN01F.
    PATTCRP                            YESN01F.
    PATTCRR                            YESN01F.
    PATTPAYD                           YESN01F.
    PATTRSA                            YESN01F.
    PATTRSH                            YESN01F.
    PATTRSL                            YESN01F.
    PATTRSP                            YESN01F.
    PATTRSR                            YESN01F.
    PBUSIND                            YESN01F.
    PDWTYP                   $         D00051F.
    PEDUCMIE                 $         D00053F.
    PEFATINC                           M00018F.
    PEFGTR                             M00018F.
    PEFMJSIF                 $         D00035F.
    PEFMTINC                           M00018F.
    PFCRN                    $         D00059F.
    PFMTYPG                  $         D00054F.
    PFRSPST                  $         D00050F.
    PFSZ                               D00061F.
    PFSZ0004                 $         YESN01F.
    PFSZ0517                 $         YESN01F.
    PFSZ1824                 $         YESN01F.
    PFSZ2544                 $         YESN01F.
    PFSZ4564                 $         YESN01F.
    PFSZ65UP                 $         YESN01F.
    PFTENUR                            D00025F.
    PNBEARG                            D00058F.
    PPVRES                   $         D00012F.
    PREGION                  $         D00052F.
    PRETIRME                 $         YESN01F.
    PSEXMIE                            SEX002F.
    PWAOTPEN                           M00036F.
    PWAPRVAL                           M00036F.
    PWARPPG                            M00036F.
    PWARPPT                            M00036F.
    PWARRIF                            M00036F.
    PWARRSPL                           M00036F.
    PWASTBND                           M00036F.
    PWASTDEP                           M00036F.
    PWASTMUI                           M00036F.
    PWASTOIN                           M00036F.
    PWASTONF                           M00036F.
    PWASTRST                           M00036F.
    PWASTSTK                           M00036F.
    PWASTVHE                           M00036F.
    PWATFS                             M00036F.
    PWATOTPG                           M00036F.
    PWATOTPT                           M00036F.
    PWBUSEQ                            M00036F.
    PWDPRMOR                           M00036F.
    PWDSLOAN                           M00036F.
    PWDSTCRD                           M00036F.
    PWDSTLOC                           M00036F.
    PWDSTODB                           M00036F.
    PWDSTOMR                           M00036F.
    PWDSTVHN                           M00036F.
    PWDTOTAL                           M00036F.
    PWEIGHT                            M00038F.
    PWNETWPG                           M00036F.
    PWNETWPT                           M00036F.
    REFATINC                 $         D00060F.
    REFGTR                   $         D00060F.
    REFMTINC                 $         D00060F.
    RWAOTPEN                 $         D00060F.
    RWAPRVAL                 $         D00060F.
    RWARPPG                  $         D00060F.
    RWARPPT                  $         D00060F.
    RWARRIF                  $         D00060F.
    RWARRSPL                 $         D00060F.
    RWASTBND                 $         D00060F.
    RWASTDEP                 $         D00060F.
    RWASTMUI                 $         D00060F.
    RWASTOIN                 $         D00060F.
    RWASTONF                 $         D00060F.
    RWASTRST                 $         D00060F.
    RWASTSTK                 $         D00060F.
    RWASTVHE                 $         D00060F.
    RWATFS                   $         D00060F.
    RWATOTPG                 $         D00060F.
    RWATOTPT                 $         D00060F.
    RWBUSEQ                  $         D00060F.
    RWDPRMOR                 $         D00060F.
    RWDSLOAN                 $         D00060F.
    RWDSTCRD                 $         D00060F.
    RWDSTLOC                 $         D00060F.
    RWDSTODB                 $         D00060F.
    RWDSTOMR                 $         D00060F.
    RWDSTVHN                 $         D00060F.
    RWDTOTAL                 $         D00060F.
    RWEIGHT                  $         D00062F.
    RWNETWPG                 $         D00060F.
    RWNETWPT                 $         D00060F.
    ;
